### ISSUE TITLE
Generated bespoken tests have formatting issues

### ISSUE THREAD

**Issue by techpeace** [voxable/cli#12]
Currently, the Simple Project example outputs these tests with `voxable bespoken:export`:

```
---
configuration:
locales: en-US

---

- test: Launch request only
- "Alexa, open Simple Project.":"Hello! I am Simple Project. You can say, \"Add a task,\" or \"cancel\" to quit. How can I help you today?"

- test: Launch request, add task
- "Alexa, open Simple Project.":"Hello! I am Simple Project. You can say, \"Add a task,\" or \"cancel\" to quit. How can I help you today?"
- "Add a task.":"Sorry, I'm not going to do that, actually. Goodbye!"

- test: Launch request, add task
- "Alexa, open Simple Project.":"Hello! I am Simple Project. You can say, \"Add a task,\" or \"cancel\" to quit. How can I help you today?"
- "Cancel.":"Goodbye!"
```

This needs to look like the following in order to pass:

```
---
configuration:
  locales: en-US
  voiceId: Joey

---
- test: Launch request only
- "Alexa, open Simple Project.": hello I am simple project you can say a task or cancel to quit how can I help you today

---
- test: Launch request, add task
- "Alexa, open Simple Project.": hello I am simple project you can say a task or cancel to quit how can I help you today
- "Add a task.": sorry I'm not going to do that actually goodbye

---
- test: Launch request, add task
- "Alexa, open Simple Project.": hello I am simple project you can say a task or cancel to quit how can I help you today
- "Cancel.": goodbye
```
